### PR TITLE
remove all contact phones and add case statement

### PR DESCRIPTION
**Pull request by hixi**
Reviewed by:
- [x] @das-g 
- [ ] @beneditatan 

Closes geometalab/osmaxx-conversion-service#84

Before actually merging this one, please have a look at #451

### CODE REVIEW

**Comment by das-g** [comment]
What about these occurrences? (Found with `git grep contact_phone`)

- osmaxx/conversion/converters/converter_gis/bootstrap/sql/filter/create_view/013_view_pow_a.sql: <pre>contact_phone,</pre>
- osmaxx/conversion/converters/converter_gis/bootstrap/sql/filter/create_view/014_view_pow_p.sql: <pre>contact_phone,</pre>
- osmaxx/conversion/converters/converter_gis/bootstrap/sql/filter/create_view/015_view_poi_a.sql: <pre>contact_phone,</pre>
- osmaxx/conversion/converters/converter_gis/bootstrap/sql/filter/create_view/016_view_poi_p.sql: <pre>contact_phone,</pre>
- osmaxx/conversion/converters/converter_gis/bootstrap/sql/filter/poi/000_setup-drop_and_recreate_table_poi_a.sql: <pre>       contact_phone text,</pre>
- osmaxx/conversion/converters/converter_gis/bootstrap/sql/filter/poi/120_setup-drop_and_recreate_table_poi_p.sql: <pre>       contact_phone text,</pre>
- osmaxx/conversion/converters/converter_gis/bootstrap/sql/filter/pow/000_setup-drop_and_recreate_table_pow_a.sql: <pre>       contact_phone text,</pre>
- osmaxx/conversion/converters/converter_gis/bootstrap/sql/filter/pow/020_setup-drop_and_recreate_table_pow_p.sql: <pre>       contact_phone text,</pre>

**Comment by hixi** [comment]
of course we should, I'll correct that omission!

**Comment by hixi** [comment]
Done.

**Comment by hixi** [comment]
Depends on #451 (that one should be merge in this one before merging this one ;-) )

**Pull request merged**
